---
format_version: 10
environments:
  test-adobe:
    pipelines:
      - cds-test
pipelines:
  cds-test:
    group: test-adobe
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      adobe:
        git: https://gitlab.com/vigneshkumar12/cdsmdc-gocd.git
        username: vigneshkumar4111999@gmail.com
        shallow_clone: false
        auto_update: false
        branch: develop
        encrypted_password: AES:OeoltL7xPkt6HEmIuCKGGQ==:PH7piPLJMtBj6TK+YJLpMQ==
    stages:
      - testing:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            test:
              timeout: 0
              resources:
                - cds-uat
              tasks:
                - exec:
                    arguments:
                      - -c
                      - docker run -v $(pwd):/app --rm
                        515481116135.dkr.ecr.ap-southeast-1.amazonaws.com/mgtcloud-deployment:latest
                        bash -c "mkdir -p /root/.ssh/ && ssh-keyscan
                        ssh.ap-3.magento.cloud >> /root/.ssh/known_hosts &&
                        ssh-keyscan git.ap-3.magento.cloud >>
                        /root/.ssh/known_hosts && git clone -b
                        integration  https://vigneshkumarra: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@github.com/centraldigital/ex-commerce-cds-mdc.git
                        deploy_repo && cd deploy_repo  && git remote add
                        magento_cloud git.ap-3.magento.cloud:vsdinyhnv5jiq.git"
                    command: /bin/bash
                    run_if: passed
