name: Quality Check

on:
  push:
    branches:
      - master
      - github
      
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - github
      
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    env:
      MAGENTO_DIR: '_CI'
      EXECUTABLE_FOLDER: 'shell'
    steps:
      - uses: actions/checkout@v2

      - name: Checkout CI repo
        uses: actions/checkout@v2
        with:
          repository: vishnuvardhanmaari/aws
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          path: ${{ env.MAGENTO_DIR }}

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.5

      - name: Defining the Env variable through _CI folder
        
        working-directory: ${{ env.MAGENTO_DIR }}
        run: "ls && git remote -v && git branch && pwd"
          

      - name: Defining the Env
        run: "ls && git remote -v && git branch && pwd"
          
      - name: Defining the Env variable through _CI folder
        env: 
          OVERRIDE_PHP_FLAG: ${{ secrets.OVERRIDE_PHP_FLAG }}
        working-directory: ${{ env.MAGENTO_DIR }}
        run: ls && ls -al && pwd 
        run: |
          if [ ${{ env.OVERRIDE_PHP_FLAG }} ]; then   
            echo "it id defined"
          else 
            echo "it is not defined"
          fi
      # - name: Set Push Environment
      #   if: steps.branch-name.outputs.is_tag == 'false' && steps.branch-name.outputs.is_default == 'true'
      #   run: |
      #     echo "BRANCH=${{ steps.branch-name.outputs.ref_branch }}" >> $GITHUB_ENV

      # - name: Set PR Environment
      #   if: steps.branch-name.outputs.is_tag == 'false' && steps.branch-name.outputs.is_default == 'false'
      #   run: |
      #     echo "BRANCH=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV

      # - name: Set Tags Environment
      #   if: steps.branch-name.outputs.is_tag == 'true'
      #   run: |
      #     echo "BRANCH=${{ steps.branch-name.outputs.tag }}" >> $GITHUB_ENV    
            
      # - name: Setup PHP with tools
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: ${{ env.PHP_VERSION }}
      #     extensions: ${{ env.PHP_EXTENSION }}
      #     tools: ${{ env.PHP_TOOLS }}
      #     coverage: xdebug    

      # - name: Add HTTP basic auth credentials
      #   working-directory: ${{ env.MAGENTO_DIR }}
      #   run: |
      #     if [ ! -f "auth.json" ]; then
      #      echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      #     fi

      # - name: Get Php extension dir
      #   run: |
      #     echo "PHP_DIR=`php-config --extension-dir`" >> $GITHUB_ENV

